name: iOS Build
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 升級到 v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Runner.app
        run: flutter build ios --release --no-codesign

      - name: Compress App for download
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../../../Runner.ipa Payload/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # 升級到 v4
        with:
          name: ios-app-bundle
          path: Runner.ipa